"""Render IMD alert-tool results as text, straight from provider data.

Alert responses are never generated by the LLM. Four different situations
are kept apart on purpose:

* actual alert data          -> the warnings, exactly as IMD reported them
* no active alerts           -> only when IMD was queried and reported none
* provider not configured    -> no IMD district ID is set for the location
* provider unavailable       -> the request failed / returned unusable data
"""

NOT_CONFIGURED_MESSAGE = (
    "Weather alert data is not configured for this location."
)

UNAVAILABLE_MESSAGE = (
    "Weather alert data is currently unavailable from the provider. "
    "Please try again later."
)

LOCATION_REQUIRED_MESSAGE = (
    "Location not detected. Please specify a city."
)

_UNAVAILABLE_STATUSES = {
    "api_error",
    "invalid_response",
    "empty_response"
}


def _is_active(alert: dict) -> bool:
    """True when an IMD day entry contains a real warning."""

    codes = alert.get("warning_codes") or []

    return bool(codes) and codes != [1]


def format_alert_response(alert_data: dict) -> str:
    """Convert a ``get_weather_alerts`` result into a user-facing message."""

    status = (alert_data or {}).get("status")

    if status == "not_configured":
        return NOT_CONFIGURED_MESSAGE

    if status == "location_required":
        return LOCATION_REQUIRED_MESSAGE

    if status in _UNAVAILABLE_STATUSES:
        return UNAVAILABLE_MESSAGE

    if status != "available":
        # Unknown / missing status: never guess.
        return UNAVAILABLE_MESSAGE

    location = alert_data.get("location") or "this location"
    issue_date = alert_data.get("issue_date")

    active = [
        alert
        for alert in alert_data.get("alerts", [])
        if _is_active(alert)
    ]

    if not active:
        return (
            f"No active weather warnings for {location} "
            "according to IMD."
        )

    heading = f"Weather alerts for {location} (IMD district warnings"

    if issue_date:
        heading += f", issued {issue_date}"

    lines = [heading + "):"]

    for alert in active:

        line = f"Day {alert['day']}: " + ", ".join(alert["warnings"])

        if alert.get("color"):
            line += f" ({alert['color']} alert)"

        lines.append(line)

    return "\n".join(lines)
