"""LLM integration.

AIService holds the prompts and validation; subclasses only implement `_complete` for their API.
Groq is the default provider; OpenAI and Gemini are kept so the team can switch with one env var.
The LLM is used for two narrow jobs:
  1. turning a question into a validated QueryIntent (structured JSON), and
  2. phrasing an answer from weather data the backend has already fetched and verified.
It is never asked for weather values, and it never receives a question without the data it needs.
"""

import json
import logging
import re
from abc import ABC, abstractmethod
from typing import Any

import httpx
from pydantic import ValidationError

from app.core.config import Settings
from app.core.exceptions import AIInvalidResponseError, AIServiceUnavailableError
from app.schemas.chat import QueryIntent
from app.services.http_client import request_json

logger = logging.getLogger(__name__)

LANGUAGE_NAMES = {
    "en": "English",
    "hi": "Hindi",
    "bn": "Bengali",
    "ta": "Tamil",
    "te": "Telugu",
    "mr": "Marathi",
    "gu": "Gujarati",
    "kn": "Kannada",
    "ml": "Malayalam",
    "pa": "Punjabi",
    "or": "Odia",
    "as": "Assamese",
    "ur": "Urdu",
}

INTENT_SYSTEM_PROMPT = """You classify weather questions for a weather app used in India.
Return ONLY a JSON object with exactly these keys:
- "intent": one of "current_weather", "forecast", "alerts", "general"
- "location": the place name mentioned in the question, written in English (e.g. "Bhopal"), or null if no place is named. Use null when the user means their own location ("here", "near me").
- "time_range": one of "now", "today", "tomorrow", "next_3_days", "next_7_days", or null
- "requires_current_weather": true if present conditions are needed
- "requires_forecast": true if future conditions are needed
- "requires_alerts": true if the user asks about warnings, alerts, storms, floods, heatwaves or safety
Use "general" only for questions that need no location-specific weather data (greetings, definitions, how the app works).
The question may be in any language; always use the values above in English.

Examples:
"Will it rain tomorrow in Bhopal?" -> {"intent":"forecast","location":"Bhopal","time_range":"tomorrow","requires_current_weather":false,"requires_forecast":true,"requires_alerts":false}
"अभी इंदौर में तापमान क्या है?" -> {"intent":"current_weather","location":"Indore","time_range":"now","requires_current_weather":true,"requires_forecast":false,"requires_alerts":false}
"Is there any storm warning near me?" -> {"intent":"alerts","location":null,"time_range":null,"requires_current_weather":false,"requires_forecast":false,"requires_alerts":true}
"What does humidity mean?" -> {"intent":"general","location":null,"time_range":null,"requires_current_weather":false,"requires_forecast":false,"requires_alerts":false}"""

ANSWER_SYSTEM_PROMPT = """You are WeatherGPT, a helpful weather assistant for people in India.
Rules you must follow:
1. Use ONLY the facts in the VERIFIED DATA JSON. Never invent, estimate or recall any weather value, alert, date or place that is not in it.
2. If the data needed to answer is missing, say plainly that you do not have that information.
3. Items under "app_advisories" are generated by this app from forecast data. They are NOT official warnings. Never call them official, IMD or government warnings.
4. Only items under "official_alerts" are official warnings. If "official_alert_status" says no provider is configured, say that official warnings could not be checked and suggest checking IMD (mausam.imd.gov.in). Do not claim there are no official warnings.
5. Quote numbers with the units given in the data. Mention the place name when known.
6. Reply in {language}. Keep it short (2-5 sentences), friendly, plain text with no markdown."""


def _strip_code_fences(text: str) -> str:
    match = re.search(r"```(?:json)?\s*(.*?)```", text, re.DOTALL)
    return (match.group(1) if match else text).strip()


class AIService(ABC):
    name: str

    def __init__(self, client: httpx.AsyncClient, timeout: float) -> None:
        self._client = client
        self._timeout = timeout

    @abstractmethod
    async def _complete(self, system_prompt: str, user_prompt: str, *, json_mode: bool) -> str:
        """Send one prompt to the provider and return the text reply."""

    async def _post(self, url: str, payload: dict[str, Any], headers: dict[str, str]) -> dict[str, Any]:
        return await request_json(
            self._client,
            "POST",
            url,
            json=payload,
            headers=headers,
            timeout=self._timeout,
            service_name="AI service",
            error_cls=AIServiceUnavailableError,
        )

    async def extract_intent(self, message: str) -> QueryIntent:
        raw = await self._complete(INTENT_SYSTEM_PROMPT, message, json_mode=True)
        try:
            return QueryIntent.model_validate(json.loads(_strip_code_fences(raw)))
        except (json.JSONDecodeError, ValidationError) as exc:
            logger.warning("%s returned an invalid intent: %s", self.name, str(exc)[:200])
            raise AIInvalidResponseError() from exc

    async def generate_answer(self, question: str, language: str, verified_data: dict[str, Any]) -> str:
        language_name = LANGUAGE_NAMES.get(language.split("-")[0], language)
        system_prompt = ANSWER_SYSTEM_PROMPT.replace("{language}", language_name)
        user_prompt = (
            f"QUESTION:\n{question}\n\n"
            f"VERIFIED DATA (JSON):\n{json.dumps(verified_data, ensure_ascii=False, default=str)}"
        )
        answer = (await self._complete(system_prompt, user_prompt, json_mode=False)).strip()
        if not answer:
            raise AIInvalidResponseError()
        return answer


class GeminiAIService(AIService):
    name = "Gemini"
    BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

    def __init__(self, client: httpx.AsyncClient, api_key: str, model: str, timeout: float) -> None:
        super().__init__(client, timeout)
        self._api_key = api_key
        self._model = model

    async def _complete(self, system_prompt: str, user_prompt: str, *, json_mode: bool) -> str:
        generation_config: dict[str, Any] = {"temperature": 0.1 if json_mode else 0.3}
        if json_mode:
            generation_config["responseMimeType"] = "application/json"
        payload = {
            "systemInstruction": {"parts": [{"text": system_prompt}]},
            "contents": [{"role": "user", "parts": [{"text": user_prompt}]}],
            "generationConfig": generation_config,
        }
        # Key goes in a header, not the URL, so it never appears in access logs.
        data = await self._post(
            f"{self.BASE_URL}/models/{self._model}:generateContent",
            payload,
            {"x-goog-api-key": self._api_key},
        )
        try:
            parts = data["candidates"][0]["content"]["parts"]
            return "".join(part.get("text", "") for part in parts)
        except (KeyError, IndexError, TypeError, AttributeError) as exc:
            logger.warning("Gemini response had no text candidates (possibly blocked): %s", str(data)[:200])
            raise AIInvalidResponseError() from exc


class OpenAICompatibleAIService(AIService):
    """Chat Completions API shared by OpenAI and Groq (Groq exposes the same request format)."""

    URL: str

    def __init__(self, client: httpx.AsyncClient, api_key: str, model: str, timeout: float) -> None:
        super().__init__(client, timeout)
        self._api_key = api_key
        self._model = model

    def _extra_options(self) -> dict[str, Any]:
        return {}

    async def _complete(self, system_prompt: str, user_prompt: str, *, json_mode: bool) -> str:
        payload: dict[str, Any] = {
            "model": self._model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.1 if json_mode else 0.3,
            **self._extra_options(),
        }
        if json_mode:
            payload["response_format"] = {"type": "json_object"}
        data = await self._post(self.URL, payload, {"Authorization": f"Bearer {self._api_key}"})
        try:
            content = data["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as exc:
            logger.warning("%s response had no message content: %s", self.name, str(data)[:200])
            raise AIInvalidResponseError() from exc
        if not isinstance(content, str):
            raise AIInvalidResponseError()
        return content


class GroqAIService(OpenAICompatibleAIService):
    name = "Groq"
    URL = "https://api.groq.com/openai/v1/chat/completions"

    def _extra_options(self) -> dict[str, Any]:
        # gpt-oss models reason before answering. Low effort keeps replies fast, and the reasoning
        # text is dropped from the response. Other Groq models reject these options.
        if self._model.startswith("openai/gpt-oss"):
            return {"reasoning_effort": "low", "include_reasoning": False}
        return {}


class OpenAIAIService(OpenAICompatibleAIService):
    name = "OpenAI"
    URL = "https://api.openai.com/v1/chat/completions"


def build_ai_service(settings: Settings, client: httpx.AsyncClient) -> AIService | None:
    """Return the configured AI service, or None if it is disabled or missing its key."""
    if settings.AI_PROVIDER == "groq" and settings.GROQ_API_KEY is not None:
        return GroqAIService(
            client, settings.GROQ_API_KEY.get_secret_value(), settings.GROQ_MODEL, settings.AI_TIMEOUT_SECONDS
        )
    if settings.AI_PROVIDER == "gemini" and settings.GEMINI_API_KEY is not None:
        return GeminiAIService(
            client, settings.GEMINI_API_KEY.get_secret_value(), settings.GEMINI_MODEL, settings.AI_TIMEOUT_SECONDS
        )
    if settings.AI_PROVIDER == "openai" and settings.OPENAI_API_KEY is not None:
        return OpenAIAIService(
            client, settings.OPENAI_API_KEY.get_secret_value(), settings.OPENAI_MODEL, settings.AI_TIMEOUT_SECONDS
        )
    return None
